import type { Metadata } from "next";
import { Inter, Roboto, Nabla } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Link from "next/link";

const inter = Inter({
    subsets: ["latin"]
});
const nabla = Nabla({
    weight: "400",
    subsets: ["latin"]
});
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={styles.main}>
                <nav className={styles.navbar}>
                    <Link href="/"
                        style={{
                            filter: "hue-rotate(90deg)"
                        }}>
                        <div style={{ fontSize: "28px" }} className={nabla.className}>
                            OMG
                        </div>
                        <div style={{ fontSize: "10px", color: "gold", letterSpacing: "1.9px" }}
                            className={roboto.className}>
                            it's Kuei
                        </div>
                    </Link>
                    <Link href="/portfolio">
                        <h2>
                            Portfolio <span className={inter.className}>-&gt;</span>
                        </h2>
                    </Link>
                    <Link href="/resume">
                        <h2>
                            Resume <span className={inter.className}>-&gt;</span>
                        </h2>
                    </Link>
                    <Link href="/about">
                        <h2>
                            About <span className={inter.className}>-&gt;</span>
                        </h2>
                    </Link>
                    <Link href="/contact">
                        <h2>
                            Contact <span className={inter.className}>-&gt;</span>
                        </h2>
                    </Link>
                </nav>
                {children}
                <footer className={styles.footer}>
                    <Link href="/sitemap" className={styles.card}>
                        <h4>
                            Sitemap
                        </h4>
                    </Link>
                    <p>Copyright © 2024 Kuei Feng Tung. All Rights Reserved.</p>
                </footer>
            </body>
        </html>
    );
}
