import type { Metadata } from "next";
import { Inter, Roboto, Nabla } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Link from "next/link";
import Image from "next/image";
import { Navbar } from "@/components/Navbar";

const inter = Inter({
    subsets: ["latin"]
});
const nabla = Nabla({
    weight: "400",
    subsets: ["latin"]
});
const roboto = Roboto({
    weight: '400',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body style={{ padding: "2px " }}>
                <Navbar></Navbar>

                <main className={styles.main}>
                    <section style={{
                        display: "flex",
                        flexDirection: "column",
                        alignItems: "center",
                        width: "100%",
                    }}>
                        {children}
                    </section>
                </main>
                <footer className={styles.footer}>
                    <Link href="/sitemap" className={styles.card}>
                        <h4 style={{ color: "lime" }}>
                            Sitemap
                        </h4>
                    </Link>
                    <div style={{
                        display: "flex",
                        flexDirection: "column"
                    }}>
                        <FooterContact platform={"LINE ID"} username={"kueifengtung"} imgSrc={"/imgs/ui/line.svg"} imgAlt={"LINE"}></FooterContact>
                        <FooterContact platform={"GitHub"} username={"omgitskuei"} imgSrc={"/imgs/ui/github.svg"} imgAlt={"GitHub"} imgInverse={true} link={"https://github.com/omgitskuei/"}></FooterContact>
                        <FooterContact platform={"Discord"} username={"omgitskuei"} imgSrc={"/imgs/ui/discord.svg"} imgAlt={"Discord"}></FooterContact>
                    </div>
                    <div>
                        <p>Copyright © 2024 Kuei Feng Tung.</p>
                        <p>All Rights Reserved.</p>
                    </div>
                </footer>
            </body>
        </html>
    );
};

const FooterContact = ({
    platform,
    username,
    imgSrc,
    imgAlt,
    imgInverse = false,
    link = ""
}: {
    platform: string,
    username: string,
    imgSrc: string,
    imgAlt: string,
    imgInverse?: boolean,
    link?: string
}) => {
    if (link != "") {
        return (
            <Link href={link}>
                <div style={{
                    display: "flex",
                }}>
                    <span style={{
                        width: "100px",
                        display: "flex",
                        alignItems: "center",
                        gap: "5px"
                    }}>
                        <Image src={imgSrc} alt={imgAlt} width={15} height={15} style={{
                            filter: imgInverse ? "invert(1)" : "none"
                        }}>
                        </Image>{platform}:
                    </span>
                    <span style={{ color: "lime" }}>
                        {username}
                    </span>
                </div>
            </Link>
        );
    } else {
        return (
            <div style={{
                display: "flex",
            }}>
                <span style={{
                    width: "100px",
                    display: "flex",
                    alignItems: "center",
                    gap: "5px"
                }}>
                    <Image src={imgSrc} alt={imgAlt} width={15} height={15} style={{ filter: imgInverse ? "invert(1)" : "none" }}></Image>{platform}:
                </span>
                <span>
                    {username}
                </span>
            </div>
        );
    }
};
